# Generated by Django 3.2.7 on 2021-09-28 14:40

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('first_name', models.CharField(blank=True, max_length=64)),
                ('last_name', models.CharField(blank=True, default='', max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='ClientSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('comment', models.TextField(blank=True, max_length=500, verbose_name='Comment')),
                ('payment_type', models.CharField(choices=[('CASH', 'CASH'), ('CARD', 'CARD')], max_length=10, verbose_name='Payment type')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client')),
            ],
            options={
                'verbose_name': 'Client Subscription',
                'verbose_name_plural': 'Client Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('datetime', models.DateTimeField(verbose_name='Time of the event')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.classroom', verbose_name='Classroom')),
                ('client_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.clientsubscription')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=64, verbose_name='First name')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('percentage', models.FloatField(default=0, verbose_name='Percentage')),
                ('lessons_qty', models.IntegerField(default=0, verbose_name='lessons_qty')),
                ('percentage_if_absent', models.FloatField(default=0, verbose_name='Percentage if absent')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_subscription_related', to='crm.user', verbose_name='Creator')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.subject')),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.AddField(
            model_name='subject',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_subject_related', to='crm.user', verbose_name='Creator'),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_place_related', to='crm.user', verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Place',
                'verbose_name_plural': 'Places',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('payment_type', models.CharField(choices=[('CASH', 'CASH'), ('CARD', 'CARD')], max_length=10, verbose_name='Payment type')),
                ('amount', models.FloatField(blank=True, default=0, verbose_name='Amount')),
                ('comment', models.TextField(blank=True, max_length=200, verbose_name='Comment')),
                ('client_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.clientsubscription')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_payment_related', to='crm.user', verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='LessonComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('comment', models.TextField(blank=True, max_length=500, verbose_name='Comment')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_lessoncomment_related', to='crm.user', verbose_name='Creator')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.lesson')),
            ],
            options={
                'verbose_name': 'Lesson comment',
                'verbose_name_plural': 'Lesson comments',
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_lesson_related', to='crm.user', verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_teacher', to='crm.user', verbose_name='Teacher'),
        ),
        migrations.AddField(
            model_name='clientsubscription',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_clientsubscription_related', to='crm.user', verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='clientsubscription',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.subscription'),
        ),
        migrations.AddField(
            model_name='clientsubscription',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_teacher', to='crm.user'),
        ),
        migrations.CreateModel(
            name='ClientComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], default='ACTIVE', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('comment', models.TextField(blank=True, default='', max_length=200, verbose_name='Comment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client', verbose_name='Client')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_clientcomment_related', to='crm.user', verbose_name='Creator')),
            ],
            options={
                'verbose_name': 'Client Comment',
                'verbose_name_plural': 'Client Comments',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_client_related', to='crm.user', verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_classroom_related', to='crm.user', verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.place'),
        ),
    ]
